# File: azure-pipelines.yml
resources:
  repositories:
  - repository: TemplatesYaml
    type: git
    name: DemoSura/TemplateYaml

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- template: requiredtask.yml@TemplatesYaml
  parameters:
    buildSteps:  
      - bash: echo Test #Passes
        displayName: Build
      
      - bash: echo "Test"
        displayName: UnitTest
      
      - bash: echo "Test"
        displayName: UnitTest
      - task: SSH@0
        inputs:
          runOptions: 'inline'
          readyTimeout: '20000'
      - task: CmdLine@2
        displayName: Test 3 - Will Fail
      - task: Bash@3
        displayName: Sonar
        inputs:
          targetType: 'inline'
          script: 'echo "Script Test2"'
      - task: Bash@3
        displayName: Pepe
        inputs:
          targetType: 'inline'
          script: 'echo "Script Test2"'