# File: azure-pipelines.yml
resources:
  repositories:
  - repository: TemplatesYaml
    type: git
    name: DemoSura/TemplateYaml

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- template: requiredtask.yml@TemplatesYaml
  parameters:
    buildSteps:  
      - bash: echo Test #Passes
        displayName: succeed
      - bash: echo "Test"
        displayName: succeed
      - task: Bash@3
        displayName: Test 3 - Will Fail
        inputs:
          script: echo "Script Test"
      - task: Bash@3
        displayName: Test 4 - Will Fail
        inputs:
          targetType: 'inline'
          script: 'echo "Script Test2"'
      - task: Bash@3
        inputs:
          runOptions: 'commands'
          readyTimeout: '20000'