# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  pipelines:
  - pipeline: MyShuttle-yaml-resource 
    source: MyShuttle-yaml

  repositories:
  - repository: TemplatesYaml
    type: git
    name: DemoSura/TemplateYaml

trigger:
  branches:
   include: 
    - 'master'
  paths:
    exclude:
      - CI

stages:
- stage: 'Deployment_Myshuttle'
  displayName: 'Deployment_Myshuttle'
  #condition: and(succeeded(),eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #dependsOn: ${{ parameters.StageDepend }}
  jobs:
  - deployment: Deployment_Myshuttle
    pool:
       vmImage: 'ubuntu-latest'
    environment: ${{ parameters.EnviromentPostApproval }}
    strategy:
      # default deployment strategy, more coming...
      runOnce:
        deploy:
          steps:

          - task: AzureCLI@2
            displayName: 'Create AppService'
            inputs:
              azureSubscription: 'sura'
              scriptType: 'batch'
              scriptLocation: 'inlineScript'
              inlineScript: '${{ parameters.ScriptAzureCli }}'

          - task: AzureRmWebAppDeployment@4
            inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'sura'
                appType: 'webAppLinux'
                WebAppName: 'MyShuttlesura'
                packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.war'
                RuntimeStack: ${{ parameters.RuntimeStack }}

- template: postdeploymentapproval.yml@InterTemplatesYaml
  parameters:
    StageDepend: 'Deployment_Myshuttle'
    EnviromentPostApproval: 'Myshuttle-dev'
