# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  repositories:
  - repository: TemplatesYaml
    type: git
    name: DemoSura/TemplateYaml

trigger:
  branches:
   include: 
    - 'master'
  paths:
    exclude:
      - CI
name: $(major).$(minor).$(patch)
extends:
  template: MavenWithSonar.yml@TemplatesYaml
  parameters:
    SonarQubeServer: 'SonarQubeSTPC'
    SonarQubeRunAnalysis: false
    MavenAuthenticateFeed: true
    JdkVersionOption: '1.8'
    MavenGoals: 'deploy'
    options: '-DskipITs -Dbuildversion=$(Build.BuildNumber)'
    buildSteps:
        - task: Maven@3
          displayName: 'Execution Maven 2222222'
          inputs:
            goals: 'package'
            options: '-DskipITs'
            codeCoverageToolOption: JaCoCo
            codeCoverageSourceDirectories: src/main
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: 1.8
            mavenOptions: '-Xmx3072m'
            mavenAuthenticateFeed: true
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
            sqMavenPluginVersionChoice: 'latest'
        - task: CmdLine@2
          inputs:
            script: |
              echo Write your commands here
              echo Hello world
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo 'Hello world'
              cd $(build.sourcesdirectory)
              ls
        - task: WhiteSource Bolt@20
          inputs:
            cwd: '$(build.sourcesdirectory)'