# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  repositories:
  - repository: TemplatesYaml
    type: git
    name: DemoSura/TemplateYaml

trigger:
  branches:
   include: 
    - 'master'
  paths:
    exclude:
      - CI

pool:
  vmImage: 'ubuntu-latest'
steps:

- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    goals: 'package'
    options: '-DskipITs'
    codeCoverageToolOption: JaCoCo
    codeCoverageSourceDirectories: src/main
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 1.8
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    sqMavenPluginVersionChoice: 'latest'

# - template: MavenWithSonar.yml@TemplatesYaml
#  parameters:
#    SonarQubeServer: 'SonarQubeSTPC'
#    SonarQubeRunAnalysis: true
#    MavenAuthenticateFeed: true
#    JdkVersionOption: '1.8'
#    MavenGoals: 'package'
#    options: '-DskipITs'
